### ISSUE TITLE
[scripts-audit] Scripts tree auditing

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#17691]
Audit all of the CMake scripts to match [the guidelines](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/cmake-guidelines.md)

## Scripts
- [ ] vcpkg_find_acquire_program: PR #21173 
- [x] vcpkg_fixup_pkgconfig: PR #19348
- [x] vcpkg_find_fortran: PR #19239
- [x] vcpkg_download_distfile: PR #19238 
- [x] vcpkg_check_linkage: PR #18981
- [x] z_vcpkg_get_cmake_vars: PR #18839 
- [x] vcpkg_copy_tool_dependencies: PR #18783
- [x] vcpkg_copy_tools: PR #18783
- [x] vcpkg_copy_pdbs: PR #16309 #18783
- [x] vcpkg_clean_executables_in_bin: PR #18783
- [x] vcpkg_build_ninja: PR #18782
- [x] vcpkg_get_program_files_platform_bitness: PR #18786
- [x] vcpkg_get_windows_sdk: PR #18786
- [x] vcpkg_minimum_required: PR #18784
- [x] vcpkg_replace_string: PR #18785
- [x] vcpkg_list: PR #18397 
- [x] vcpkg_execute_build_process: PR #18488
- [x] vcpkg_execute_in_download_mode: PR #18488
- [x] vcpkg_execute_required_process_repeat: PR #18488
- [x] vcpkg_execute_required_process: PR #18488
- [x] vcpkg_extract_source_archive_ex: PR #18517
- [x] vcpkg_extract_source_archive: PR #18517
- [x] vcpkg_from_bitbucket: PR #18272
- [x] vcpkg_from_git: PR #18272
- [x] vcpkg_from_github: PR #18272
- [x] vcpkg_from_gitlab: PR #18272
- [x] vcpkg_from_sourceforge: PR #18272
- [x] ports.cmake: PR #16257
- [x] vcpkg.cmake: PR #16061
- [x] execute_process: PR #16190
- [x] vcpkg_acquire_msys: PR #17687
- [x] vcpkg_add_to_path: PR #16189
- [x] vcpkg_apply_patches: PR #16304
- [x] vcpkg_buildpath_length_warning: PR #16191
- [x] vcpkg_check_features: PR #16192
- [x] vcpkg_common_definitions: PR #16393
- [x] vcpkg_common_functions: PR #
- [x] vcpkg_fail_port_install: PR #18054 
- [x] vcpkg_fixup_cmake_targets: PR #16377
- [x] vcpkg_test_cmake: PR #16257
- [x] z_vcpkg_apply_patches: PR #18013 
- [x] z_vcpkg_escape_regex_control_characters: PR #18013 
- [x] z_vcpkg_function_arguments: PR #16193
- [x] z_vcpkg_prettify_command_line: PRs #16195, #16130

### Buildsystems

- [x] make: PR #20165
  - vcpkg_build_make
  - vcpkg_configure_make
  - vcpkg_install_make
- [x] meson: PR #21026
  - vcpkg_configure_meson
  - vcpkg_install_meson
- [x] nmake: PR #20987 
  - vcpkg_build_nmake
  - vcpkg_install_nmake
- [x] qmake: PR #20322
  - vcpkg_build_qmake
  - vcpkg_configure_qmake
  - vcpkg_install_qmake
- [x] CMake: PRs #16377, #18843 #20885
  - vcpkg_build_cmake
  - vcpkg_configure_cmake
  - vcpkg_install_cmake
- [x] msbuild: PR #17779
  - vcpkg_build_msbuild
  - vcpkg_clean_msbuild
  - vcpkg_install_msbuild
- [x] gn: PR #17776
  - vcpkg_build_gn
  - vcpkg_configure_gn
  - vcpkg_install_gn

**Comment by BillyONeal** [comment]
Because there is only one outstanding PR left I'm going to track this as that PR; closing this issue. See https://github.com/microsoft/vcpkg/pull/21173 for the last bit.

Thanks @strega-nil !
