### ISSUE TITLE
vcpkg tool development documentation checklist

### ISSUE THREAD

**Issue by ubsan** [microsoft/vcpkg#7368]
Checklist for myself for writing documentation:

- [ ] new test framework
  - [ ] running tests (CMake + Ninja/make/VS)
  - [ ] running tests (VS)
  - [ ] writing tests
- [ ] layout of the project
  - [ ] VS build files
  - [ ] CMake build files
  - [ ] include structure
  - [ ] source structure
